## Bayes Classifier Practice

In [3]:
import numpy as np

In [30]:
# prior probability
P1 = 0.33
P2 = 0.67

In [31]:
# mean
mu1 = np.array([5.01,3.42])
mu2 = np.array([6.26,2.87])

In [32]:
# covariance matrix
cov1 = np.array([0.122,0.098,0.098,0.142]).reshape(2,2)
cov2 = np.array([0.435,0.121,0.121,0.110]).reshape(2,2)

In [33]:
# new data point
x = np.array([6.75,4.25])

In [34]:
# likelihood
# fx for class 1
fx11 = 1/(np.sqrt(2*np.pi)**2*np.sqrt(np.linalg.det(cov1)))  

fexp11 = np.matmul((x-mu1).T,np.linalg.inv(cov1))
fexp12 = np.matmul(fexp11,x-mu1)
fx12 = np.exp(-fexp12/2)

fx1 = fx11*fx12

In [35]:
# likelihood
# fx for class 2
fx21 = 1/(np.sqrt(2*np.pi)**2*np.sqrt(np.linalg.det(cov2)))  

fexp21 = np.matmul((x-mu2).T,np.linalg.inv(cov2))
fexp22 = np.matmul(fexp21,x-mu2)
fx22 = np.exp(-fexp22/2)

fx2 = fx21*fx22

In [36]:
# probability of observing x from any of the k classes,
p = fx1*P1 + fx2*P2

In [37]:
#  posterior probability
p1x = fx1*P1/p
p2x = fx2*P2/p

print("P(y=1|x) = {0:.2f}".format(p1x))
print("P(y=2|x) = {0:.2f}".format(p2x))

P(y=1|x) = 0.01
P(y=2|x) = 0.99


In [29]:
A = np.array([1,23,45,34,34,56,34,12,8,7,10,4]).reshape(4,3)
A

array([[ 1, 23, 45],
       [34, 34, 56],
       [34, 12,  8],
       [ 7, 10,  4]])

$$ 
cov(X,Y) = \sum_{n=i}^N\frac{(x_i - \bar{x})(y_i - \bar{y})}{N}
$$

In [27]:
covA = np.cov(A.T)
print(covA)

[[306.          52.          34.        ]
 [ 52.         122.91666667 281.08333333]
 [ 34.         281.08333333 682.91666667]]


In [28]:
mu = np.mean(A.T,1)
print(mu)

[19.   19.75 28.25]
